In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
globalwarming_df=pd.read_csv('C:\\Users\\mriaz\\machine learning\\seaborn\\Who_is_responsible_for_global_warming.csv')
globalwarming_df

,Country Name,Country Code,Indicator Name,Indicator Code,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014
0,United States,USA,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,20.178751,19.636505,19.613404,19.564105,19.658371,19.591885,19.094067,19.217898,18.461764,17.157738,17.442862,16.976957,16.310471,16.323477,16.502837
1,United Kingdom,GBR,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,9.199549,9.233175,8.904123,9.053278,8.989140,8.982939,8.898710,8.617164,8.424424,7.574622,7.857836,7.079298,7.355898,7.145844,6.497440
2,India,IND,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,0.979870,0.971698,0.967381,0.992392,1.025028,1.068563,1.121982,1.193210,1.310098,1.431844,1.397009,1.476686,1.598099,1.591438,1.730000
3,China,CHN,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2.696862,2.742121,3.007083,3.524074,4.037991,4.523178,4.980314,5.334910,5.701915,6.010102,6.560520,7.241515,7.424751,7.557211,7.543908
4,Russian Federation,RUS,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,10.627121,10.669603,10.715901,11.090647,11.120627,11.253529,11.669122,11.672457,12.014507,11.023856,11.694348,12.334881,12.784979,12.393556,11.857528
5,Australia,AUS,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,17.200610,16.733367,17.370452,16.901959,17.026515,17.169711,17.651398,17.865260,18.160876,18.200182,17.740845,17.538878,17.072905,16.095833,15.388766
6,France,FRA,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,5.946665,6.153061,6.068664,6.115998,6.120079,6.099599,5.906266,5.766385,5.690501,5.438357,5.428981,5.077911,5.075064,5.062174,4.573182
7,Germany,DEU,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,10.095640,10.366287,10.058673,9.969355,9.898682,9.666372,9.911476,9.488040,9.506321,8.818596,9.279634,9.124859,9.199300,9.390623,8.889370
8,Canada,CAN,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,17.367115,16.985030,16.559378,17.461199,17.258911,17.251083,16.696694,16.855883,16.875198,15.961560,15.723167,15.639760,14.890636,14.711972,15.117159
9,Brazil,BRA,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,1.871118,1.898354,1.844380,1.762482,1.828672,1.858088,1.839394,1.901372,2.008670,1.883812,2.132938,2.211587,2.343570,2.488417,2.594388
10,Argentina,ARG,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,3.835574,3.568600,3.291548,3.525584,4.069058,4.141237,4.434821,4.382669,4.682912,4.410890,4.558500,4.600291,4.569384,4.462904,4.746797
11,Pakistan,PAK,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,0.768458,0.764702,0.788668,0.804959,0.872802,0.887768,0.929857,0.991030,0.972050,0.950832,0.946268,0.929801,0.918978,0.904316,0.896264
12,Nepal,NPL,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,0.129282,0.135226,0.106877,0.113902,0.105477,0.120277,0.098812,0.099736,0.129224,0.162087,0.187128,0.202491,0.211798,0.237170,0.283539
13,Bangladesh,BGD,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,0.211802,0.242020,0.246756,0.256602,0.266823,0.275247,0.299529,0.301631,0.332728,0.357159,0.393937,0.412011,0.433488,0.442401,0.459142
14,Japan,JPN,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,9.622352,9.464309,9.573130,9.725282,9.909203,9.698883,9.632049,9.782964,9.449534,8.620816,9.148316,9.317427,9.638628,9.780815,9.538706